title: Welcome to My Blog
author: Apeksha Haveri
email: apekshahaveri93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my travel blog. Here you will explore more about the travel,stay and places to visit in Maldives.

# social links
github_username:  apekshaih # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: Merlot
